steps:
  - name: node
    id: test and compile the function
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm install && npm test && npm run build
    dir: "functions/notify-github"

  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy the function
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud functions deploy notify-github --runtime nodejs16 --trigger-http --region us-central1 --entry-point notifyGithub
    dir: "functions/notify-github"
