main:
  params: [input]
  steps:
    - getSha:
        assign:
          - sha: ${input.sha}
        next: pendingGithub

    - pendingGithub:
        call: http.post
        args:
          url: https://australia-southeast1-cloud-pipeline-dev.cloudfunctions.net/notify-github
          auth:
            type: OIDC
          body:
            sha: ${sha}
            repo: "workflow-cicd-demo"
            owner: "jgunnink"
            state: "pending"
            context: "Workflow CD"
            description: "Pipeline running..."
            workflowId: ${sys.get_env("GOOGLE_CLOUD_WORKFLOW_EXECUTION_ID")}

    - hasWorkflowChanged:
        try:
          call: googleapis.cloudbuild.v1.projects.triggers.run
          args:
            projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
            triggerId: determineDifferences
            body:
              commitSha: ${sha}
              substitutions:
                _COMPARISON: "workflow.yaml"
          next: hasCodeChanged
        except:
          next: updateWorkflow

    - updateWorkflow:
        try:
          call: googleapis.cloudbuild.v1.projects.triggers.run
          args:
            projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
            triggerId: ensureWorkflowCurrent
            body:
              commitSha: ${sha}
        except:
          as: error
          assign:
            - pipelineError: ${error}
          next: failGithub

    - hasCodeChanged:
        try:
          call: googleapis.cloudbuild.v1.projects.triggers.run
          args:
            projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
            triggerId: determineDifferences
            body:
              commitSha: ${sha}
              substitutions:
                _COMPARISON: "functions/notifyGithub"
            next: succeedGithub
        except:
          next: deployCode

    - deployCode:
        try:
          call: googleapis.cloudbuild.v1.projects.triggers.run
          args:
            projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
            triggerId: deployCode
            body:
              commitSha: ${sha}
          next: succeedGithub
        except:
          as: error
          assign:
            - pipelineError: ${error}
          next: failGithub

    - succeedGithub:
        call: http.post
        args:
          url: https://australia-southeast1-cloud-pipeline-dev.cloudfunctions.net/notify-github
          auth:
            type: OIDC
          body:
            sha: ${sha}
            repo: "workflow-cicd-demo"
            owner: "jgunnink"
            state: "success"
            context: "Workflow CD"
            description: "Pipeline successful"
            workflowId: ${sys.get_env("GOOGLE_CLOUD_WORKFLOW_EXECUTION_ID")}
        next: end

    - failGithub:
        call: http.post
        args:
          url: https://australia-southeast1-cloud-pipeline-dev.cloudfunctions.net/notify-github
          auth:
            type: OIDC
          body:
            sha: ${sha}
            repo: "workflow-cicd-demo"
            owner: "jgunnink"
            state: "failure"
            context: "Workflow CD"
            description: ${pipelineError.operation.error.message}
            workflowId: ${sys.get_env("GOOGLE_CLOUD_WORKFLOW_EXECUTION_ID")}
