main:
  params: [input]
  steps:
  - getSha:
      assign:
        - sha: ${input.commits[0].id}
      next: pendingGithub
  - pendingGithub:
      call: http.post
      args:
        url: https://australia-southeast1-cloud-pipeline-dev.cloudfunctions.net/notify-github
        body:
          sha: ${sha}
          repo: "workflow-cicd-demo"
          owner: "jgunnink"
          state: "pending"
          context: "Workflow CD"
          description: "Pipeline running..."
      next: succeedGithub
  - succeedGithub:
      call: http.post
      args:
        url: https://australia-southeast1-cloud-pipeline-dev.cloudfunctions.net/notify-github
        body:
          sha: ${sha}
          repo: "workflow-cicd-demo"
          owner: "jgunnink"
          state: "success"
          context: "Workflow CD"
          description: "Pipeline successful"

