main:
  params: [input]
  steps:
    - init:
        assign:
          - sha: ${input.sha}
          - pipelineError: null
        next: pendingGithub

    - pendingGithub:
        call: http.post
        args:
          url: https://us-central1-cloud-pipeline-dev.cloudfunctions.net/notify-github
          auth:
            type: OIDC
          body:
            sha: ${sha}
            repo: "workflow-cicd-demo"
            owner: "jgunnink"
            state: "pending"
            context: "Workflow CD"
            description: "Pipeline running..."
            workflowId: ${sys.get_env("GOOGLE_CLOUD_WORKFLOW_EXECUTION_ID")}

    - hasInfrastructureChanged:
        try:
          call: googleapis.cloudbuild.v1.projects.triggers.run
          args:
            projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
            triggerId: determine-differences
            body:
              commitSha: ${sha}
              substitutions:
                _COMPARISON: "terraform"
        except:
          steps:
            - LogUpdateWorkflow:
                call: sys.log
                args:
                  text: Workflow change detected. Updating workflow.
                next: updateWorkflow
        next: hasCodeChanged

    - updateWorkflow:
        try:
          call: googleapis.cloudbuild.v1.projects.triggers.run
          args:
            projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
            triggerId: deploy-infrastructure
            body:
              commitSha: ${sha}
        except:
          as: pipelineError
          steps:
            - LogFailedWorkflowUpdate:
                call: sys.log
                args:
                  text: Update workflow failed. Failing to github.
                next: failGithub
        next: hasCodeChanged

    - hasCodeChanged:
        try:
          call: googleapis.cloudbuild.v1.projects.triggers.run
          args:
            projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
            triggerId: determine-differences
            body:
              commitSha: ${sha}
              substitutions:
                _COMPARISON: "functions/notify-github"
        except:
          steps:
            - LogCodeChangeDetected:
                call: sys.log
                args:
                  text: Code change detected, performing update.
                next: deployCode
        next: succeedGithub

    - deployCode:
        try:
          call: googleapis.cloudbuild.v1.projects.triggers.run
          args:
            projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
            triggerId: deployCode
            body:
              commitSha: ${sha}
        except:
          as: pipelineError
          steps:
            - LogFailedCodeDeployment:
                call: sys.log
                args:
                  text: Code deployment failed with error.
                next: failGithub
        next: succeedGithub

    - succeedGithub:
        call: http.post
        args:
          url: https://us-central1-cloud-pipeline-dev.cloudfunctions.net/notify-github
          auth:
            type: OIDC
          body:
            sha: ${sha}
            repo: "workflow-cicd-demo"
            owner: "jgunnink"
            state: "success"
            context: "Workflow CD"
            description: "Pipeline successful"
            workflowId: ${sys.get_env("GOOGLE_CLOUD_WORKFLOW_EXECUTION_ID")}
        next: end

    - failGithub:
        call: http.post
        args:
          url: https://us-central1-cloud-pipeline-dev.cloudfunctions.net/notify-github
          auth:
            type: OIDC
          body:
            sha: ${sha}
            repo: "workflow-cicd-demo"
            owner: "jgunnink"
            state: "failure"
            context: "Workflow CD"
            description: ${pipelineError.operation.error.message}
            workflowId: ${sys.get_env("GOOGLE_CLOUD_WORKFLOW_EXECUTION_ID")}
