steps:
  - name: node
    id: test and compile the function
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm install && npm test && npm run build
    dir: "functions/gitops"

  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy the function
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud functions deploy ts-template --gen2 --runtime=nodejs16 --trigger-http --allow-unauthenticated --region australia-southeast1 --entry-point=gitops
    dir: "functions/gitops"
